### ISSUE TITLE
New release wished for

### ISSUE THREAD

**Issue by alexmyczko** [thestk/rtmidi#165] opened 2018-07-12 10:31 UTC
I would like to see a new version released, so it can get into Debian early, to eventually/maybe get Fasttracker II packaged properly, without a local unreleased actual copy of rtmidi.

Would that be do-able during the next 3 months?

**Comment by radarsat1** [comment] 2018-07-12 13:04
I think it should be possible.  But you've got me curious as an avid FT2 user from 20 years ago, I didn't know FastTracker II was even available for Linux let alone being packaged for Debian.  Where can I find out more about this?

**Comment by alexmyczko** [comment] 2018-07-12 13:32
https://16-bits.org/ft2.php

**Comment by radarsat1** [comment] 2018-07-14 23:14
Cool stuff!

Anyways, on topic: After reviewing I think there have been sufficient changes that a release is in order.  Ideally we could fix the long-standing issues with port naming, but it doesn't warrant blocking a release imho.  I'd like to integrate the fixes to the automake build system I've proposed, and then decide what to do regarding version numbers.

A quick glance shows that technically apart from some bug fixes, we've only added a couple of new functions so I'm not sure a major version bump is necessary, but on the other hand the visibility of some symbols may have changed.  I'll have to take a deeper look.

**Comment by garyscavone** [comment] 2018-07-15 11:22
What are the specifics of the previously mentioned c-wrapper callback bug? Can someone provide a fix for this before a new release is made?

**Comment by radarsat1** [comment] 2018-07-15 21:42
Yes, so just to be clear, it has been fixed, @8bitbubsy just wants the fix to be in a tagged release.

Fix was in 431354f421855739d57ec07cd132d8ef14484e4e

I will have a hard look in the next days at the C API to see if there are any bugs to be fixed or improvements that can be made.

I'll also give a harder look to the previous efforts to fix the port naming scheme -- I think the reason we haven't fixed/accepted things on this front is mainly the difficulty of verifying a fix.  We want something that works reliably across APIs and operating systems, but this means testing with many different computers and MIDI devices, which is a hard effort to organize.  I think the best approach would be to come up with something backwards-compatible that can be improved/fixed incrementally, but it is not easy.

**Comment by garyscavone** [comment] 2018-07-17 10:46
The port-naming issue is indeed a long-standing problem, with no easy cross-platform solution. There have been previous proposals (from 4 years ago or more) but they often involved a lot of extra “baggage.” From what I remember, the problem is primarily related to “plug and play” devices (reordering) and drivers that don’t necessarily distinguish multiple devices of the same type / model.

**Comment by sagamusix** [comment] 2018-08-13 18:40
Slightly off-topic: Even without 431354f it is possible to use the old C API though; it can be determined easily from the high nibble of the first message byte how long the message is (apart from SysEx, which the FT2 clone probably doesn't handle anyway). `strlen` is quite obviously the wrong solution because we are not dealing with strings here but with MIDI messages.

**Comment by alexmyczko** [comment] 2019-02-11 11:05
6 months passed, any update?

**Comment by radarsat1** [comment] 2019-04-18 12:07
Release 4.0.0 has been issued.

**Closed by radarsat1** 2019-04-18 12:07 UTC
