### ISSUE TITLE
Remove RtMidi Deltatimes

### ISSUE THREAD

**Issue by midimusic** [thestk/rtmidi#125] opened 2017-09-27 08:11 UTC
I have been using RtMidi to input streams of midi events from
several midi input ports and combining them by using only one common
userCallback function. (A circular FIFO buffer would be a better
method of combining but the common callback function does work).

I wanted to use the userCallback to record a midi file of the combined
midi streams.

Deltatime is defined as the time between two sequential midi events. A midi
file records and uses deltatimes to implement its timing function (speed of
playback, or tempo).

A feature of deltatme is that if you add all the deltatimes together you
should always recover the original total time.

However I soon struck a problem with RtMidi's delta times -- adding them up
DOES NOT recover the original time, not even approximately. Even deltatimes
from just one midi input did not add correctly. (Using Windows 10. I cannot
vouch for other API's but suspect all until proved otherwise).

Adding together deltatimes from two or more combined inputs is so wildly wrong that
it is impractical to use them for any purpose.

Additionally RtMidi internally converts 32 bit unsigned ints to double for
output to the userCallback function. In order for the user to use these doubles
they have to be converted back to 32 bit unsigned ints. What a waste of processing
time, very important for real time midi events -- every microsecond wasted is
one that cannot be used to do something useful.

As I suspect that NOBODY has ever used RtMidi's deltatimes successfully I propose
that they ought to be removed.

It is easier and better to use a continuously incremented 1 or 2 ms timer for timing
midi events. I have proved that this works, using the same timer for both recording
and replay of midi files.

David.

The maintainers / developers of RtMidi favour pull requests over issues. We generally do not have access to all the supported platforms to attempt to verify a reported problem. It will help the entire RtMidi community if you can debug a problem you are reporting and suggest a way to fix it yourself.

- Expected behavior and actual behavior.

- Steps to reproduce the problem.

- Specifications like the version of the project, operating system, or hardware.

**Comment by radarsat1** [comment] 2017-09-27 13:15
David,

No offense intended, but please don't be ridiculous.  In #124 you have raised a bug regarding delta times, which I understood to some degree and attempted to fix for you.  Apparently that was not sufficient, and you posted some code (not as a PR i might add but as an attachment), which I haven't had time to look at yet.  Unfortunately none of the maintainers of RtMidi have a full time jobs working on RtMidi, and we also don't have easy access to a variety of test setups including all combinations of all operating systems and MIDI hardware, so you'll have to excuse us if we depend rather a lot on community help to detect and fix bugs.

Regarding your point about conversion, converting to time in seconds is seen as a good compromise across APIs, and doubles should have sufficient representation for pretty accurate time representation down to a few microseconds, with a drift of less than a microsecond after about an hour.  About drift, the fact that MIDI files rely on time differences is a problem with MIDI, not with RtMidi.  Rounding to 1 or 2 milliseconds also introduces error, depending on the OS.  That said I am open to a debate on the issue, if you have strong arguments for doing it differently (across all platforms), but that should be raised in a dedicated issue.

As for CPU time used by the conversion, if this is really concerning to you then I submit that you should not be using RtMidi at all.  The goals of RtMidi are to make it *easy* to use MIDI in a cross-platform way with little hassle.  It is not intended as a performance beast.  If your MIDI application depends on that kind of performance then you should be working directly with the API of your platform and not wasting time on the overhead of RtMidi's queues etc.

Finally, on "merging" multiple incoming streams with the same callback, I suggest that this may be a use case that hasn't been tested with RtMidi, so if you have suggestions or bugs to report please open dedicated issues and PRs accordingly.

In any case we can continue to work on the delta time issue in #124, so I'm closing this as removing a feature entirely because of a bug under certain conditions that happen to be specific to your project is out of the question and obviously simply due to some frustration on your part.  I entirely understand your frustration but there is no reason to castrate the project for it.  (Unless we work on things further and determine that it is *actually* unresolvable, but I have strong doubts about that.)

One concrete thing you *could* do, and I'll raise it in #124, that would help with this problem *for everyone* and not just Windows users, is to submit a test program that identifies the issue and fails if delta times are not correctly calculated under a variety of conditions.  Similar reasoning goes for the stream-merging issue.

**Closed by radarsat1** 2017-09-27 13:15 UTC

**Comment by radarsat1** [comment] 2017-09-27 17:32
So, I promised in #124 that I would address your points more specifically.  As I said there, I do not think there are "fundamental flaws" but rather bugs that should be addressed.

> However I soon struck a problem with RtMidi's delta times -- adding them up
DOES NOT recover the original time, not even approximately. Even deltatimes
from just one midi input did not add correctly.

So this seems like an empirical result that could be reproduced.  The question is,

1. do you think this is related to what you are doing regarding "merging" the callback for multiple open ports?  To be honest I am not 100% sure you mean when you suggestion multiple streams, as you haven't provided an example.

2. Or is this problem with delta times present also when using a single MIDI in port?

3. Is it only when there are filtered messages, or does it exist otherwise as well?

**Comment by midimusic** [comment] 2017-09-27 20:16
The errors occurring on one midi input are all due to various bugs. I never tried your updated
patch because, as I said before it completely stopped my organ working when I compiled it in.
I now know that I forgot to #define any api so this was definitely one reason why it did not work.
I never got round to trying it again but I do not think it would work for LONGDATA because
of the complexity of getting it right which you had not addressed. Especially -- what happens
when LONGERRORS occur. This is very complex and would need a flow chart to get the design
right.

I guarantee that my patched RtMidi.cpp will work correctly under Windows for deltatime under
all situations. However I purposely stopped it from accepting LONGDATA and LONGERRORS
because I did not need them in order to make my organ record midi (which was my main interest).

The fundamental flaw occurs when you merge two or more midi inputs -- it makes no difference how
you do it, If you add the deltatimes from both inputs the result will always be too large because
the sum of EACH ONE will be the total time, thus the sum of two inputs will be 2 * total time.
This makes the deltatimes worthless. How do you arrive at the proper deltatimes for the merged
inputs? -- I do not know, and it would be too complicated to be worth doing (unless you
can prove otherwise), especially as I have said before midi can be recorded more easily using
a contiuous timer.

For these reasons I advocated removing deltatimes from RtMidi.  They are complex to
get right and even if you do get them right there is never going to be any reason to use them.

I will leave you to ponder this before responding to any of your other comments.

David.

**Comment by radarsat1** [comment] 2017-09-27 20:21
If you could please explain very clearly what you mean by "merge two or more midi inputs" it would help immensely.  Do you mean two ports?  Or you have two keyboards plugged in and two instances of RtMidiIn?  *Exactly* what do you mean, in terms of RtMidi usage?  Or in terms of Windows API usage if you please.

**Comment by midimusic** [comment] 2017-09-28 13:49
I am talking about merging the inputs from two ports which have been input via two
instances of RtMidi. The flaw applies generally and is not specific to Windows.

**Comment by radarsat1** [comment] 2017-09-29 21:56
But the timestamp should be local to the RtMidi instance.. I don't see how they could get mixed up.  I'll have to do some experiments.

Unless you are talking about correctly interleaving the deltas from two streams.  In that case it's something one would do outside of RtMidi I think.  It could be an interesting example to put together.  It should be the same algorithm as merging two MIDI files.

**Comment by midimusic** [comment] 2017-09-30 15:15
I am NOT talking about merging the deltas from two midi streams. Merging the deltas
is not easy and is a complete waste of effort (even if they worked properly).

I AM talking about recording the results of merging two midi streams. The deltatimes
you are producing are of no value in this case because of the fundamental flaw. It is
easy to record the midi (merged or otherwise) using a continuous clock.

I do not see what you find so difficult to understand - your deltatmes have never
worked properly and have NEVER been used for any useful purpose by ANYBODY.
Because they are completely redundant -- NOBODY has ever needed them because
they MAY be of value ONLY if you are recording midi and midi can be recorded just
as easily without any need for them.

**Comment by radarsat1** [comment] 2017-10-01 00:06
Your reply prompted me to go back and re-read your description of the "fundamental flaw".  With due respect, I think there is a problem in your reasoning which is maybe why we differ on this topic.

> The fundamental flaw occurs when you merge two or more midi inputs -- it makes no difference how
you do it, If you add the deltatimes from both inputs the result will always be too large because
the sum of EACH ONE will be the total time, thus the sum of two inputs will be 2 * total time.

Why would you add the delta times from two different streams? That is not the correct way to merge two streams.  The correct way is to track the absolute time for *each* stream (by summing them independently), then you have the absolute time of each MIDI event.  Then you calculate new deltas for the merged stream by re-differentiating the common clock.  This is currently not something that RtMidi can do, but it should be possible to use the delta times given by getMessage() to do it yourself (untested):

~~~
void recordTwoStreams()
{
  RtMidiIn* rtin[2];
  // ... initialize rtin[0] and rtin[1] ...
  double absolute[2] = {0,0}, lasttime = 0;
  std::vector< std::vector< unsigned char > > messages;
  std::vector< double > deltatimes;
  std::vector<unsigned char> msg;
  while (1)
  {
    for (int i=0; i<2; i++)
    {
      double delta = rtin[i]->getMessage(&msg);
      if (msg.size() > 0) {
        absolute[i] += delta;
        messages.push_back(msg);
        deltatimes.push_back(absolute[i] - lasttime);
        lasttime = absolute[i];
      }
    }
    SLEEP(10);
  }
  // merged stream is in (deltas, messages)
}
~~~

Of course it is predicated on getMessage() returning correct delta times.

**Comment by radarsat1** [comment] 2017-10-01 00:26
I'll just add, before you point it out, that the above solution of course relies on a synchronised common reference clock for both open ports, and correction for any initial difference in their initial times.  In that light I would identify the following issues:

1. Ensure delta times are well-tested on all platforms and fixed if necessary. (Already open as #124.)
2. Investigate on all platforms whether a mechanism for ensuring a common clock for multiple ports is possible. (e.g. the callback could be implemented as a singleton if necessary); reduce "delta drift" as much as possible.  I don't expect relative timing to be a problem but if a common callback between ports is possible it should be taken advantage of.
3. Record and provide an accessor for the "start time" of a MIDI stream, so that offsets between streams' t=0 can be corrected-for relative to other streams.

Of these (2) is probably the most difficult but I don't expect it's strictly necessary either, as I don't expect much clock drift between streams.

**Comment by garyscavone** [comment] 2017-10-01 02:04
Just my two cents here but RtMidi was only designed to support one open port at a time. When I started to write it, I quickly realized that it would be too complicated to attempt to have each RtMidi instance support more than one port. Thus, all the timing issues necessary to merge multiple ports are the responsibility of the user, not the RtMidi developers.  Yes, the delta times need to work for a given port but beyond that, the user is own her/his own.

If I was trying to synchronize multiple input ports, I would first open them, then find a way to have all ports receive a common input message, and from those, figure out the time lag between them.

**Comment by midimusic** [comment] 2017-10-01 13:11
This is getting unbelievably complicated for doing something which is so simple.

I have already solved the problem of merging two or more midi inputs to my
satisfaction. As I have said several times the deltatimes from RtMidi are simply NOT NEEDED
in order to utilize or record the combined result.

To radarsat1:

I doubt if any complicated and time consuming method of merging midi inputs (even if it works)
would be useful for any purpose which requires the fastest possible execution times necessary --
as do most real time projects. (Including my organ -- I have to process each incoming
midi stream during the time it takes for the next on to arrive -- this includes setting
stops, playing multiple streams of audio and recording and playing midi at the same time.)

To garyscavone:

My organ has six midi inputs which arrive via six ports -- I use a separate instance of RtMidi
for each one. I am currently combining these inputs simply by using the same userCallback
for all of them. I am also feeding the output from four onscreen keyboards and onscreen
stop setting facilities (touch screen) and output from a midi player into the same userCallback.
Much to my surprise it all works and plays really complex organ music in real time.

David.

**Comment by radarsat1** [comment] 2017-10-01 23:18
> I have already solved the problem of merging two or more midi inputs to my satisfaction.

Okay I'll stop worrying about this issue then and concentrate on testing delta times for all platforms in #124.  Thanks!
