### ISSUE TITLE
Windows 10 input deltatime

### ISSUE THREAD

**Issue by midimusic** [thestk/rtmidi#124] opened 2017-09-22 12:09 UTC
I am using Windows 10 with MinGW32 c++ compiler.

I am using RtMidi to input multiple midi ports into my own design of
3 manual + pedal organ. There is one common RtMidi callback. 

The organ is working OK. I now wish to record
midi files from the manual inputs and am using RtMidi's deltatime
inputs. I have ignoreTypes(false, false, true); on all inputs.

The problem is that the deltatimes I get are more or less random and
bear little relation to the actual times. I have a midi keyboard
connected and if I press a key for 5 seconds I would expect to see
a 5 second deltatime. This is not the case. The deltatimes displayed
are never more than 0.300000 and are usually displayed similar to
0.125000, never more than 3 significant figures.

My display code is inside the RtMidi callback as below:
char buffer[80];
sprintf(buffer, " %lf \r\n", deltatime);
SetWindowText(hMainEdit,buffer);

If I use the callback to record a midi file the correct notes play but
note timing is all over the place.

I have tested the Windows midi in ports using a command line program
and it shows the 32bit int ms times from opening the port are as expected.

I have looked at your RtMidi source code which is compiled from source
along with the rest of my program and can see nothing obviously wrong.

Has anybody actually used this timing on windows 10?

Thanks for your help.
David.

The maintainers / developers of RtMidi favour pull requests over issues. We generally do not have access to all the supported platforms to attempt to verify a reported problem. It will help the entire RtMidi community if you can debug a problem you are reporting and suggest a way to fix it yourself.

- Expected behavior and actual behavior.

- Steps to reproduce the problem.

- Specifications like the version of the project, operating system, or hardware.

**Comment by radarsat1** [comment] 2017-09-22 13:19
I haven't used it, but it seems the timing data is taken from the timestamp provided by the MIDI callback, which is defined as [Time that the message was received by the input device driver](https://msdn.microsoft.com/en-us/library/windows/desktop/dd757284(v=vs.85).aspx) in milliseconds starting from zero when midiInStart was called.

The time difference calculation is then, `(double) ( timestamp - apiData->lastTime ) * 0.001`, which seems correct to me.  So unless the driver is reporting wrong timestamps I can't see an obvious problem.  However, you mention,

> I have tested the Windows midi in ports using a command line program and it shows the 32bit int ms times from opening the port are as expected.

Can you expand on this?  Do you have the source for this program?  It would be good to know what it is doing differently.

Can you test using both the RtMidi callback and queue methods?  (cmidiin and qmidiin examples, respectively..)

**Comment by radarsat1** [comment] 2017-09-22 13:23
Ah, I was just reviewing issues and maybe it is related to #82.  i.e., there are messages coming in that are filtered, but the filtering is not considered in the timestamp calculation.  If true this may be a bug in other drivers as well.  Can you confirm by playing with the filters that there are other messages coming in?  I think there is an easy fix in moving the timestamp calculation to after the message filtering.

**Comment by radarsat1** [comment] 2017-09-22 13:53
I have pushed a potential fix on master, can you check that it fixes the issue?  I have tested it on OS X but not on Windows.

**Comment by midimusic** [comment] 2017-09-22 15:11
Thanks for the information. I have moved the deltatime display code right back into
RtMidi where the values are generated. The time errors are still there. However I have
noted that there is a callback every 0,270000 seconds even when there is no midi input.
I think this is the cause of the problem as the time is getting reset at the WRONG times.

What you have said above may be relevant and I will download and try your new master
as soon as I can.

Thanks.

**Comment by midimusic** [comment] 2017-09-23 10:11
[midiin.zip](https://github.com/thestk/rtmidi/files/1326447/midiin.zip)
I have attached the source code of the midiin program I mentioned above.

I have looked at your updated master. Your change does not address the real problem and
thus will not cure it. I have now had time to think about the problem and realize
that you are not protecting the deltatime calculation from invalid data.
lParam is valid only when MIM_DATA, MIM_ERROR, MIM_LONGDATA or
MIM_LONGERROR are valid.

deltatime is the time difference between the midi EVENTS, which I have listed
above. It is NOT the time between callbacks which is what you are calculating.

BEWARE that any changes you make must preserve the sysex code you already
have as this code is VERY fragile and nearly all of the information available
about how to program midi sysex reception on windows is WRONG. Your
code is right at the moment and does work.

David

**Comment by midimusic** [comment] 2017-09-24 11:01
Having now had a more detailed (but still not comprehensive) look at
your Windows midi in callback function and done some more experiments
I have further isolated the REAL problem.

The repetitive callbacks at 0.27 seconds were active sensing messages coming
from my keyboard which you are rejecting later in your code. However
you are still using the deltatimes calculated BEFORE rejecting the messages.

Delta times MUST be calculated ONLY for messages which are ADDED TO THE
QUEUE.

There may still be a problem with sysex messages which are optional. However
the above rule still applies.

Good luck
David

**Comment by radarsat1** [comment] 2017-09-24 13:41
> Delta times MUST be calculated ONLY for messages which are ADDED TO THE QUEUE.

Hi, so my patch moves the last-saved timestamp to right before the message is added to the queue, so I'm not sure how it doesn't achieve that.  The timestamps should now be calculated based on the current timestamp and the timestamp of the last message added to the queue, as you suggest.  Perhaps I made a mistake, but I can't see it and can't test it.  Since you seem to be competent to verify my work, would you be able to propose a fix?

**Comment by midimusic** [comment] 2017-09-24 17:22
Hi radarsat1
Thanks for your update. The crux of the matter is in the second sentence of the rule in
my last post. This is very important.

I do not think your patch achieves this. I am afraid I only looked at your code and could
see that the update still calculated the delta time wrongly so I never bothered to actually
test it because I did not expect it to work.

I have already made a rough patch to my RtMidi.cpp code which as far as I can tell works
correctly -- but it applies ONLY to MIM_DATA events. As I suggested above adapting this
patch to work with MIM_LONGDATA is non trivial. For the present I will leave someone else
[rtmidi.zip](https://github.com/thestk/rtmidi/files/1327501/rtmidi.zip)

to do this  because I have only looked at a very small part of your code and do
not pretend to understand it. Getting my organ to work record and play midi is more
important.

I will attach a copy of my patched RtMidi code but it is not fit for publication without
further attention.

Best Wishes and thanks for your help.
David.

**Comment by midimusic** [comment] 2017-09-26 10:11
My patch did allow me to use deltatime to successfully write midi files but I have now
decided that it will be more practical to ignore deltatime and use a global continuous
timer for recording midi. Deltatimes from multiple inputs feeding a common userCallback
cannot be easily synchronised and thus do not work correctly.

Another Problem, still Windows 10 but applicable to other API's.

I want to use RtMidi to "side load" midi events, such as the output from the
midi player, directly into

static void CALLBACK midiInputCallback(...);

without ever opening the port. The object being to allow concurrent events generated within
my program to be processed without colliding with external events arriving via ports.

I plan to add a function to RtMidi which will use code similar to the
following (copied from your code): 

    // Copy bytes to our MIDI message.
    unsigned char *ptr = (unsigned char *) &midiMessage;
    for ( int i=0; i<nBytes; ++i ) apiData->message.bytes.push_back( *ptr++ );

    RtMidiIn::RtMidiCallback callback = (RtMidiIn::RtMidiCallback) data->userCallback;
    callback( apiData->message.timeStamp, &apiData->message.bytes, data->userData );

I will use an additional instance of RtMidi for this purpose and continue to use the same
userCallback for all inputs including this one.

Has anybody else done anything similar and will it work? In particular will it solve
the concurrency problem?

Please think carefully, you know your code MUCH better than me. This is important and may
be useful to others as well.

Thank you
David.

**Comment by radarsat1** [comment] 2017-09-26 16:01
I would like to fix your deltatime issue, as that is almost certainly a bug, however I haven't had time to examine your suggestion yet. Your point about "Deltatimes from multiple inputs feeding a common userCallback cannot be easily synchronised and thus do not work correctly" is very interesting and should perhaps be opened as a separate issue.

> I want to use RtMidi to "side load" midi events, such as the output from the midi player

Why don't you just make a separate function that is called by your midiInputCallback, instead of trying to make that function take input from extra sources?

> Please think carefully, you know your code MUCH better than me. This is important and may
be useful to others as well.

You know your needs and your bugs much better, however, and none of the maintainers have a Windows machine currently available for testing, so I would strongly encourage you to make bug fixes / suggestions through pull requests whenever possible.  The concreteness of actual code changes makes discussion a lot more straight-forward.

**Comment by radarsat1** [comment] 2017-09-27 13:26
As mentioned in #125, it might help to submit a self-contained, cross-platform test program that detects this problem, if it's at all possible.

**Comment by midimusic** [comment] 2017-09-27 15:33
Hi radarsat1

I think you are probably more frustrated than me. As I said in #125 I have no further interest
in RtMidi's deltatimes because they are fundamentally flawed -- reasons are in #125. I suggest
you spend a moment to try and understand the reason which is nothing to do with the bugs
I found.

Regarding microsecond errors, midi simply does not and never has worked to such accuracy.
A resolution and accuracy of one or two milliseconds is sufficient for all music. Using doubles to store
deltatimes which are seldom more than s few seconds is overkill of the highest degree.

You stated above:
""Deltatimes from multiple inputs feeding a common userCallback cannot be easily synchronised and thus do not work correctly" is very interesting and should perhaps be opened as a separate issue."

This is what I thought I had done in #125!!!

I do not have the time to solve your problems myself as I am too busy with producing
my organ. If there is nobody else will to help then I suggest we close the whole matter.
David.

**Comment by radarsat1** [comment] 2017-09-27 17:18
> As I said in #125 I have no further interest in RtMidi's deltatimes because they are fundamentally flawed -- reasons are in #125.

I am not convinced regarding how it is fundamentally flawed.  We can continue the discussion about it there so I can respond more specifically to your points.

> This is what I thought I had done in #125!!!

You suggested removing the feature entirely in #125. That is hardly productive.  I am hoping for a suggestion on how to resolve the issue, or a suggestion for how users might accomplish that goal should they have it.  If your only suggestion is to remove the delta times feature, then closing it was the right thing regardless, as there is nothing more to do.

> I do not have the time to solve your problems myself as I am too busy with producing
my organ. If there is nobody else who will help then I suggest we close the whole matter.

I think it's worth keeping this open until we can verify that delta times are calculated correctly, or it can be proved that such is absolutely impossible.  The latter conclusion makes no sense to me, so I think the former must be achievable somehow, even if that means resolving so-called "fundamental flaws."  It is just software. It can be changed.

As mentioned, one way to move forward on the issue would be to provide a program that has an expected behaviour under the conditions you want to see working.  If you are uninterested in continuing that is fine, you need only to simply stop responding and I will get the message.  No harm no foul.  But I think the issue you raised is perfectly valid which is why I am still discussing it.

**Comment by radarsat1** [comment] 2017-09-27 18:00
Now I am looking at the diff for the rtmidi.cpp that you provided.  The changes I see that are relevant are the following:

1. In openPort, you added a call to midiInReset() before midiInStart().  The comment says "according to Microsoft", can you link the relevant documentation?

2. You moved the code calculating the timestamp to inside `if ( inputStatus == MIM_DATA )`, to just before the comment "Copy bytes to our MIDI message."

3. You removed the early return if the callback is not called for MIM_LONGDATA, or MIM_LONGERROR, but left it for MIM_DATA.

So, for (1) maybe it is needed, I have no idea.  I'll have to read about it.

For (2), this seems to be very similar to my commit https://github.com/thestk/rtmidi/commit/67804750a5aa9034d578b8073f29eb4dffd4f333
except that I only moved the "lastTime" assignment to *after* the `if` construct instead of leaving it inside.  At least for MIM_DATA, I don't see the difference really, as in the case of my patch, the same time would be calculated, since apiData->lastTime would be the same.  With MIM_LONGDATA and MIM_LONGERROR perhaps it causes issues, I am not sure.

For (3), I assume you are trying to ignore SYSEX here.  So I assume you are referring to the fact that considering SYSEX messages makes this more complicated.  I am not sure why, however.  Since you seem knowledgeable on how SYSEX should be handled: are delta times of events following SYSEX messages supposed to be based on the timestamp of the first or the last received MIM_LONGDATA "event" ?

> deltatime is the time difference between the midi EVENTS, which I have listed above. It is NOT the time between callbacks which is what you are calculating.

This was true before, but after my commit (6780475) which you say "still calculated the delta time wrongly", it saves the last time from the last *accepted* message, since all filtered cases do an early return before the timestamp is saved.  So I would like to know why it still calculates the delta time wrongly, and why your rtmidi.cpp does not.

For clarity, here is a diff from the current RtMidi.cpp callback and yours.  As you can see the main difference is that the last timestamp is saved *inside* the `if` instead of after it.  **Is this the main problem?**

~~~diff
--- rtmidi-callback-master.cpp	2017-09-27 14:54:21.647299280 -0300
+++ rtmidi-callback-david.cpp	2017-09-27 14:54:14.351468388 -0300
@@ -9,19 +9,12 @@
                                         DWORD_PTR midiMessage,
                                         DWORD timestamp )
 {
-  if ( inputStatus != MIM_DATA && inputStatus != MIM_LONGDATA && inputStatus != MIM_LONGERROR ) return;
+  if(inputStatus != MIM_DATA) return;  //ignore all except data
 
   //MidiInApi::RtMidiInData *data = static_cast<MidiInApi::RtMidiInData *> (instancePtr);
   MidiInApi::RtMidiInData *data = (MidiInApi::RtMidiInData *)instancePtr;
   WinMidiData *apiData = static_cast<WinMidiData *> (data->apiData);
 
-  // Calculate time stamp.
-  if ( data->firstMessage == true ) {
-    apiData->message.timeStamp = 0.0;
-    data->firstMessage = false;
-  }
-  else apiData->message.timeStamp = (double) ( timestamp - apiData->lastTime ) * 0.001;
-
   if ( inputStatus == MIM_DATA ) { // Channel or system message
 
     // Make sure the first byte is a status byte.
@@ -48,6 +41,14 @@
       return;
     }
 
+  // Calculate time stamp.
+  if ( data->firstMessage == true ) {
+    apiData->message.timeStamp = 0.0;
+    data->firstMessage = false;
+  }
+  else apiData->message.timeStamp = (double) ( timestamp - apiData->lastTime ) * 0.001;
+  apiData->lastTime = timestamp;
+
     // Copy bytes to our MIDI message.
     unsigned char *ptr = (unsigned char *) &midiMessage;
     for ( int i=0; i<nBytes; ++i ) apiData->message.bytes.push_back( *ptr++ );
@@ -81,17 +82,20 @@
     else return;
   }
 
-  // Save the time of the last non-filtered message
-  apiData->lastTime = timestamp;
-
   if ( data->usingCallback ) {
     RtMidiIn::RtMidiCallback callback = (RtMidiIn::RtMidiCallback) data->userCallback;
     callback( apiData->message.timeStamp, &apiData->message.bytes, data->userData );
   }
   else {
     // As long as we haven't reached our queue size limit, push the message.
-    if (!data->queue.push(apiData->message))
-      std::cerr << "\nMidiInWinMM: message queue limit reached!!\n\n";
+    if ( data->queue.size < data->queue.ringSize ) {
+      data->queue.ring[data->queue.back++] = apiData->message;
+      if ( data->queue.back == data->queue.ringSize )
+        data->queue.back = 0;
+      data->queue.size++;
+    }
+    else
+      std::cerr << "\nRtMidiIn: message queue limit reached!!\n\n";
   }
 
   // Clear the vector for the next input message.
~~~

Again, thanks for any clarify you can provide David.

**Comment by radarsat1** [comment] 2018-07-19 01:36
This old discussion led to at least one commit but the overall point was not clearly resolved. Closing for now, it can be reopened if desired to follow up on it again.

**Closed by radarsat1** 2018-07-19 01:36 UTC
