### ISSUE TITLE
Get client name API ?

### ISSUE THREAD

**Issue by stuaxo** [thestk/rtmidi#54] opened 2015-10-20 14:38 UTC
In alsa I can get the midi client names
`alias lsmidi='aplaymidi -l'`

```
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
 20:0    APC MINI                         APC MINI MIDI 1
128:0    TiMidity                         TiMidity port 0
128:1    TiMidity                         TiMidity port 1
128:2    TiMidity                         TiMidity port 2
128:3    TiMidity                         TiMidity port 3
```

Is there any way to get the client name ?  - if not would it be possible to add a way ?

**Comment by garyscavone** [comment] 2015-11-05 13:30
Hi Stuart,

If it can be done via aplaymidi, it can be done in RtMidi.  The main issue would be finding a way to work it into the existing RtMidi API. I suppose the easiest way might be to add an optional string pointer argument to the getPortName() function that can be filled by the function if the client name is available (not all APIs will support that).  So, something like:

std::string getPortName (unsigned int portNumber=0, std::string *clientName=0 )

Regards,

—gary

**Comment by stuaxo** [comment] 2015-11-05 14:03
I was originally asking for an API in a consuming API (mido), hopefully the author will chip in if this looks good.

**Comment by olemb** [comment] 2015-11-24 13:16
Mido author here.

That should work. I could do something like this in Mido:

    get_input_names(client='something')

For this to work we also need to involve the author of python-rtmidi since Mido doesn't use RtMidi directly.

Stuart: This would give you a list of ports for a specific client. Is that what you were looking for or do you need all ports on all clients?

**Comment by SpotlightKid** [comment] 2015-11-24 13:38
I'm subscribed to updates on this project.

I've been meaning to do a new python-rtmidi release for quite some time now anyway and to get it out of beta status. I just haven't found the time to write documentation yet.

**Comment by stuaxo** [comment] 2015-11-24 16:49
@olemb I think so - I've been making something for the APC MINI ... and when I do ```aplaymidi -l``` I get
```
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
 20:0    APC MINI                         APC MINI MIDI 1
128:0    TiMidity                         TiMidity port 0
128:1    TiMidity                         TiMidity port 1
128:2    TiMidity                         TiMidity port 2
128:3    TiMidity                         TiMidity port 3
```

so if I could do ```get_input_names(client='APC MINI ')``` it should fit... I don't have more than one APC MINI, but reckon it should work.

**Comment by olemb** [comment] 2015-12-01 11:36
@SpotlightKid Awesome! Does the API look OK to you?

**Comment by SpotlightKid** [comment] 2015-12-01 13:19
@olemb That should work. I'll just add `client_name=None` as a keyword arg to `rtmidi.MidiIn.get_port_name()` and `rtmidi.MidiOut.get_port_name()` (may raise `NotImplementedError` if used with the wrong API) and add support for it to `rtmidi.midiutil.open_midiport()`.

If you want, you can open an issue [here](https://github.com/SpotlightKid/python-rtmidi/issues).

**Comment by olemb** [comment] 2015-12-15 14:38
Sounds good. This will be very easy to add to Mido once it's supported in RtMidi and python-rtmidi.

**Comment by SpotlightKid** [comment] 2015-12-15 14:49
So who writes a patch? I'm not really a C/C++ programmer. :)

**Comment by SpotlightKid** [comment] 2016-02-04 16:13
Any news on this?

**Comment by garyscavone** [comment] 2016-02-10 18:29
Someone needs to work on the implementation and submit a pull request.

**Comment by aib** [comment] 2016-09-14 08:49
The problem is that RtMidi (and therefore python-rtmidi) already returns client names. Without any port names. On the ALSA (asound) backend, the string returned is of the form "cname cid:pid".

This is also why the python-rtmidi unit tests fail on ALSA.

It would be trivial to change this, but there's no telling what it would break downstream and I wouldn't submit a PR without a green light from an RtMidi developer.

**Comment by radarsat1** [comment] 2016-09-15 15:29
> It would be trivial to change this, but there's no telling what it would break downstream and I wouldn't submit a PR without a green light from an RtMidi developer.

vs.

> Someone needs to work on the implementation and submit a pull request.

Please feel free to submit a PR  ;)

**Comment by garyscavone** [comment] 2017-08-21 19:03
Not sure where this stands but if it hasn't been fixed by now, it must not be that important.

**Closed by garyscavone** 2017-08-21 19:03 UTC

**Comment by stuaxo** [comment] 2017-08-21 21:15
Not sure if it is because of you closing this, but it looks like the upstream patch to return actual port names has just been merged.
