### ISSUE TITLE
debian patches

### ISSUE THREAD

**Issue by miramikes** [thestk/rtmidi#131] opened 2017-10-07 01:15 UTC
Hello

I am just working on rtmidi update in debian.
There are some patches we are applying in debian against rtmidi package.
Please consider if some of them might be applied upstream.

best regards

mira

[0001-buildsystem.txt](https://github.com/thestk/rtmidi/files/1364190/0001-buildsystem.txt)
[0005-fix_pkg-config.txt](https://github.com/thestk/rtmidi/files/1364191/0005-fix_pkg-config.txt)
[0006-hardening.txt](https://github.com/thestk/rtmidi/files/1364192/0006-hardening.txt)
[0007-cross.txt](https://github.com/thestk/rtmidi/files/1364193/0007-cross.txt)

**Comment by radarsat1** [comment] 2017-10-08 14:04
Hi @miramikes, thank you it's very nice to get some communication with downstream.  I'll take a look.

**Comment by miramikes** [comment] 2017-10-08 18:43
Thank you, just let me know if some patches need some more explanation.
BTW I just send one patch to rtaudio too

mira

**Comment by radarsat1** [comment] 2017-10-09 13:32
Thanks these are nice fixes for some things that have bugged me and other people.  A couple of things:

1. The visibility-default stuff is new to me. It makes it so that only the class constructors are available by symbol?  Are other class members then accessed by some id?  I'm happy to apply this if it is correct but I am confused by why only the constructors.  How do I know how to properly apply this in the future?  (Are the tests we have sufficient?)
2. Regarding CXXFLAGS, the configure.ac wrongly overrides it completely, it must be fixed, however your fix just puts it back to how it was.  Actually the reason to override it is to be able to replace `-O2` with `-O0` for debug builds.  How do other projects do this?  Should we filter the options string using sed, or something?

**Comment by radarsat1** [comment] 2017-10-09 14:12
And just out of curiosity, I don't really understand the `PC_FILE` part:

```
AC_SUBST(PC_FILE, [rtmidi.pc])
...
AC_CONFIG_FILES($PC_FILE:rtmidi.pc.in)] , )
```

Isn't that already the default behaviour of AC_CONFIG_FILES?  Or is it because the proposed `pc_requires` is not taken into account in the first invocation?  Would it make more sense to simply move AC_CONFIG_FILES from the top to immediately before AC_OUTPUT?

**Comment by radarsat1** [comment] 2017-10-09 14:38
In fact I don't actually see where `pc_requires` is used.  There is `@req@` used in rtmidi.pc.in, was it intended to replace this?

**Comment by miramikes** [comment] 2017-10-09 14:56
Hi,
first of all I have to confess that I don't have strong coding skills.
Second I am not author of 0001-buildsystem.patch and I am very unsure what is really fixing.
This patch has been applied before I became rtmidi maintainer.
Please you decide if there is something useful and if not I will drop it with next debian upload.

mira

**Comment by umlaeute** [comment] 2017-10-09 15:40
(chiming in here, as i was just preparing a PR with effectively the same patches)

- the `visibility` flag works similar to the famous `__declspec(dllexport)` on windows, in that it prevents any symbols that are not explicitely marked as being exported from being visiblie outside of the library (thus preventing name-clashes and accidental use of private symbols). it marks the entire class as being exported, not just the ctor.


- I have no clue about the `PC_FILE` magic; personally I would remove that part of the patch as cruft.
i agree that `pc_requires` seems to have been replaced by `req` (or vice versa);
i guess the point of all this is to separate the `CPPFLAGS` for building RtMidi from those required to build applications using RtMidi. There's also `api` which comes into play here. hmpf!

- could you elaborate on the `CXXFLAGS` problems?
The general expectation of the `CXXFLAGS` variable (and `CFLAGS`, `CPPFLAGS`, `LDFLAGS` ,...) is, that it can be used to inject flags into the build-process by the person who runs the build. (rather than the author). Debian makes heavy use of this.
Those flags are supposed to override any flags set by the build-system (*you*), so you should alway *prepend* any build-system specific flags. e.g.: `CXXFLAGS = ${cxxflag} ${CXXFLAGS}` (that's because the last competing flag wins. e.g. `-O0 -O3` is the same as `-O3`).
It's the users responsibility to not break the build by fuddling around with these flags, but they should be allowed to do so *easily*.

**Comment by radarsat1** [comment] 2017-10-09 16:31
> the visibility flag works similar to the famous __declspec(dllexport) on windows

Got that part, but I don't understand why it's necessary to mark the constructors and only the constructors.  I was wondering if it is that the constructors are the minimum symbol lookup needed to create the class instance.  In any case I've never used `declspec(dllexport)` with C++, only with C functions, so I'll take your word for it.
I guess what I don't understand is why the default behaviour of everything being public needs to change, as it works fine as it is.  Although it does make sense to me to hide the backend symbols, so maybe it is the right thing to do.

> i guess the point of all this is to separate the CPPFLAGS for building RtMidi from those required to build applications using RtMidi.

Understand that, just asking about the specifics here which I found a bit curious.  I think it's correct but I was surprised to see a new variable defined which is then not used.  I'll fix it if it's a mistake, no problem, just checking.

> There's also api which comes into play here. hmpf!

I actually think probably this information is better not given to user programs, they are supposed to be backend-independent at compile time.  What do you think? Should user programs know which backend is selected by the installed RtMidi?  (The info is accessible at run time regardless..)

> Those flags are supposed to override any flags set by the build-system (you), so you should alway prepend any build-system specific flags. e.g.: CXXFLAGS = ${cxxflag} ${CXXFLAGS} (that's because the last competing flag wins. e.g. -O0 -O3 is the same as -O3).

That makes sense, but the reason this was done afaik was to make it possible to add an easy `--enable-debug` option.  I'm sure there is a more standard way to do so.

In any case the issue is that if you *prepend* `-O0`, then the default CXXFLAGS which has `-O2` wins.  I guess the thing is to append *only* in the `--enable-debug` case, but any other things should be prepended.

**Comment by umlaeute** [comment] 2017-10-09 19:00
On 10/09/2017 06:31 PM, Stephen Sinclair wrote:
>> the visibility flag works similar to the famous __declspec(dllexport) on windows
> 
> Got that part, but I don't understand why it's necessary to mark the constructors and only the constructors.  I was wondering if it is that the constructors are the minimum symbol lookup needed to create the class instance.  In any case I've never used `declspec(dllexport)` with C++, only with C functions, so I'll take your word for it.
> I guess what I don't understand is why the default behaviour of everything being public needs to change, as it works fine as it is.  Although it does make sense to me to hide the backend symbols, so maybe it is the right thing to do.


i think you are misreading the code.

    class RTMIDI_DLL_PUBLIC RtMidiIn : public RtMidi { ... }

really marks the *class* to be public, rather than the ctor.
(although i haven't checked the actual binary).


> 
>> There's also api which comes into play here. hmpf!
> 
> I actually think probably this information is better not given to user programs, they are supposed to be backend-independent at compile time.  What do you think? Should user programs know which backend is selected by the installed RtMidi?  (The info is accessible at run time regardless..)

disclaimer: i'm not really using RtMidi in my projects.
however, i see that RtMidi.h is *full* of things like "#ifdef
__UNIX_JACK__", which makes the header file very much dependent on the
available backends. the header file *is* the API. so any consumer must
be aware of the available backends to (fully) use the API.
this might be a design choice. or a bug, i don't know.

btw, what i *do* know is, that preprocessor-defines starting with two
underscores are [*reserved* for the
system](https://stackoverflow.com/a/22027287/1169096).
so __UNIX_JACK__ should really be renamed to RTMIDI_HAVE_UNIX_JACK or
similar.

> 
>> Those flags are supposed to override any flags set by the build-system (you), so you should alway prepend any build-system specific flags. e.g.: CXXFLAGS = ${cxxflag} ${CXXFLAGS} (that's because the last competing flag wins. e.g. -O0 -O3 is the same as -O3).
> 
> That makes sense, but the reason this was done afaik was to make it possible to add an easy `--enable-debug` option.  I'm sure there is a more standard way to do so.

i have to admit that i haven't really found a standard way for "proper"
debug builds. Since autotools really only work nicely if you go with the
flow, me conclusion is to not try too hard to make this work.

> In any case the issue is that if you *prepend* `-O0`, then the default CXXFLAGS which has `-O2` wins.  I guess the thing is to append *only* in the `--enable-debug` case, but any other things should be prepended.
hmm. i don't really think so.
thd debug-mode is already useful, even without "-O0" (as it sets the
__RTMIDI_DEBUG__ define (again, please remove the double-underscore prefix).
as a coder, i haven't found too many (if any) bugs that would have been
discovered only with "-g -O0" but not with "-g -O2", so i doubt the
importance of that flag in the first place.
but then, ymmv.

anyhow, i found a little discussion on he [automake
mailinglist](http://gnu-automake.7480.n7.nabble.com/Why-I-can-not-overwrite-CXXFLAGS-values-td4782.html)
which basically says:

> you can modify $CXXFLAGS within configure.ac; find out
> whether CXXFLAGS was set by the user _before_ AC_PROG_CXX, and if it
> wasn't, you can default it to your liking.

which sounds correct: only modify the CXXFLAGS if they haven't been set
by the user.

**Comment by umlaeute** [comment] 2017-10-09 19:06
btw, i'm going to open a PR that includes the patches. then they can be reviewed more easily

**Comment by radarsat1** [comment] 2017-10-09 19:31
> > class RTMIDI_DLL_PUBLIC RtMidiIn : public RtMidi { ... }

> really marks the *class* to be public, rather than the ctor.

sure but what about the other part?

> -RtMidiOut :: RtMidiOut( RtMidi::Api api, const std::string &clientName)
> +extern RTMIDI_DLL_PUBLIC RtMidiOut :: RtMidiOut( RtMidi::Api api, const std::string &clientName)

I'm curious whether other functions need to be marked this way or if there is something special about the constructors.

**Comment by radarsat1** [comment] 2017-10-09 19:33
> i see that RtMidi.h is *full* of things like "#ifdef __UNIX_JACK__", 

you're right!  although I don't think those classes are meant to be used.  Probably they shouldn't be in the header file.  I wonder if there is any code in the wild that uses them..

**Comment by umlaeute** [comment] 2017-10-09 21:21
I searched for all of the backend-specific classes on https://codesearch.debian.net and at least in Debian there does not seem to be any use of things like `MidiInJack` (or `MidiOutCore`, or ...).

there's a couple of packages in Debian that use RtMidi (and RtAudio), so that is at least promising.

for the record, the actual search string was something like `-path:.*RtMidi.h  -path:.*RtMidi.cpp  MidiInCore\b` (this filters out the verbatim copies of RtMidi in the various packages).

**Comment by umlaeute** [comment] 2017-10-10 07:46
please close this issue, it has been superseded by #133 and #134.

**Closed** 2017-10-10 13:48 UTC
