### ISSUE TITLE
Novation LaunchKey Mini not detected. 

### ISSUE THREAD

**Issue by Patrik356b** [thestk/rtmidi#85] opened 2016-08-29 11:39 UTC
I'll update this with details in the next day

**Comment by radarsat1** [comment] 2016-08-29 15:35
I actually have this exact keyboard!  Haven't tried it with RtMidi yet, but I guess I can help you debug .. ;)

**Comment by Patrik356b** [comment] 2016-08-29 15:38
Awesome. I will post the details tonight. But I'm running your sample code
for input and output directly in my main atm. I'm planning to separate the
communication to a different cpp file but haven't done that yet

**Comment by Patrik356b** [comment] 2016-08-29 21:46
![rtmidi](https://cloud.githubusercontent.com/assets/2000703/18068576/49a9d846-6e42-11e6-8a03-2cb4bdff4c35.png)

```int main()
{
	std::cout << "\n Application start\n";
	
	// MIDI
	RtMidiIn  *midiin = 0;
	RtMidiOut *midiout = 0;
	// RtMidiIn constructor
	try {
		midiin = new RtMidiIn();
	}
	catch (RtMidiError &error) {
		error.printMessage();
		exit(EXIT_FAILURE);
	}
	// Check inputs.
	unsigned int nPorts = midiin->getPortCount();
	std::cout << "\nThere are " << nPorts << " MIDI input sources available.\n";
	std::string portName;
	for (unsigned int i = 0; i<nPorts; i++) {
		try {
			portName = midiin->getPortName(i);
		}
		catch (RtMidiError &error) {
			error.printMessage();
		}
		std::cout << "  Input Port #" << i + 1 << ": " << portName << '\n';
	}
	// RtMidiOut constructor
	try {
		midiout = new RtMidiOut();
	}
	catch (RtMidiError &error) {
		error.printMessage();
		exit(EXIT_FAILURE);
	}
	// Check outputs.
	nPorts = midiout->getPortCount();
	std::cout << "\nThere are " << nPorts << " MIDI output ports available.\n";
	for (unsigned int i = 0; i<nPorts; i++) {
		try {
			portName = midiout->getPortName(i);
		}
		catch (RtMidiError &error) {
			error.printMessage();
		}
		std::cout << "  Output Port #" << i + 1 << ": " << portName << '\n';
	}
	std::cout << '\n';

	// do something?

}```

**Comment by Patrik356b** [comment] 2016-08-29 21:49
As i'm coming from quirky C variants, the C++ understanding might be a bit off at some points.

**Comment by radarsat1** [comment] 2016-08-29 21:49
Hm you're not giving a lot of details of your setup, but from the font can I assume you are using Windows?
It seems that there are no MIDI devices detected, I am not sure this is specific to the keyboard.  Are you able to use other MIDI devices on your computer with RtMidi?  How about other MIDI devices with other programs?  Are you able to use your keyboard with other programs?  It is really _only_ a problem between RtMidi and your keyboard, or can you rule out other things?

**Comment by radarsat1** [comment] 2016-08-29 21:50
Oh I just noticed it is using the dummy devices, so that would be a good explanation..  you have to configure RtMidi with the back-end for your operating system.

**Comment by Patrik356b** [comment] 2016-08-29 21:52
The keyboard is working fine, i'm using Windows 8.1 x64 and MidiOX as well as Ableton Live can detect it just fine. I thought i mentioned this in the first post. But i guess i forgot to submit my edit.

**Comment by radarsat1** [comment] 2016-08-29 21:53
Did you try the program on OS X or Windows or both?  I'm guessing you have to pass it a flag during ./configure if it is not detecting it right.  It should choose CoreMIDI on OS X, and .. whatever Windows uses on Windows.

**Comment by radarsat1** [comment] 2016-08-29 21:54
yeah, for windows, the flag is `--with-winmm`, and for OS X, it is `--with-core`.  Usually it should be detected automatically, so if it's not work perhaps it can't find the headers, which is more likely in the Windows case.

**Comment by Patrik356b** [comment] 2016-08-29 21:55
No mac OS available for me. I'm not sure what it would go under on windows.

**Comment by Patrik356b** [comment] 2016-08-29 22:05
winmm.lib and --with-winmm added, no difference. Couldn't find multithreaded though. I'm using Visual Studio 2015 though with default compiler, win32 console project.

**Comment by Patrik356b** [comment] 2016-08-29 22:13
![midiox](https://cloud.githubusercontent.com/assets/2000703/18069294/87e62d72-6e46-11e6-846e-aa75fd410dbc.png)

**Comment by garyscavone** [comment] 2016-08-29 23:41
The only way you could end up with the MidiInDummy class is if no realtime support was compiled in. So, the problem is in the compiling.

**Comment by Patrik356b** [comment] 2016-08-29 23:46
I'm not sure how to get around the dummy. Originally i thought it was a wrapper. Following the instructions wasn't enough.

**Comment by garyscavone** [comment] 2016-08-29 23:51
You have to define the preprocessor definition __WINDOWS_MM__ in the Visual Studio environment when compiling. You will also have to provide linking with the winmm library.  I don’t use VS, so I cannot be of further help with the compiling process.

**Comment by Patrik356b** [comment] 2016-08-29 23:53
Those are already put in, it makes no difference,

**Comment by garyscavone** [comment] 2016-08-29 23:56
Impossible … otherwise, you wouldn’t be compiling the RtMidiDummy class.

**Comment by Patrik356b** [comment] 2016-08-30 00:18
![ss-libs](https://cloud.githubusercontent.com/assets/2000703/18071655/ffee4d98-6e57-11e6-95bd-e84b17dccd43.png)
![ss-preprocessor](https://cloud.githubusercontent.com/assets/2000703/18071656/fff2bcc0-6e57-11e6-8671-bbbd109f90e2.png)

Impossible huh?.

**Comment by garyscavone** [comment] 2016-08-30 00:26
—with-winmm is not a preprocessor definition.  It needs to be __WINDOWS_MM__ (note two underscores at beginning and end, one underscore in the middle).

The “—with-winmm” flag is for the configure script, but that is not something you should be using if you want to work in the VS domain.

**Comment by Patrik356b** [comment] 2016-08-30 00:29
Then I misunderstood the setup. I'll give it a try tomorrow

**Comment by radarsat1** [comment] 2016-08-30 00:34
Yeah sorry, it's been a while for vs for me too. In my instructions I assumed you were using mingw, sorry about that. @garyscavone is right, change where you put --with-winmm to __WINDOWS_MM__.

**Comment by radarsat1** [comment] 2016-08-30 00:35
`__WINDOWS_MM__` that is

**Comment by Patrik356b** [comment] 2016-08-30 22:04
![http://puu.sh/qUkIv/0ffa384628.png](http://puu.sh/qUkIv/0ffa384628.png)

Success. (As soon as i rebuilt rtmidi and my own project)

**Comment by radarsat1** [comment] 2016-08-30 22:31
Great! I'll close this then ;)  have fun

**Closed by radarsat1** 2016-08-30 22:31 UTC
